import { NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { prisma } from '@/lib/prisma';
import { dispatchWebhookEvent, type WebhookDeliveryAttempt } from '@/lib/webhooks';

export const dynamic = 'force-dynamic';

// Programmatic exercise of the auto-fulfill + webhook engine
// (src/lib/sandboxAutoFulfill.ts, src/lib/webhooks.ts) without waiting on
// SANDBOX_AUTO_STEP_DELAY_MS — every hop here is driven immediately so the
// request returns synchronously with a full report. Every asset created by
// this endpoint is tagged metadata.sandboxScenario/sandboxRunId, which is
// what /api/cron/sandbox-purge and /api/sandbox/status key off of.

type Scenario = 'happy_path' | 'carrier_failure' | 'webhook_timeout' | 'bulk_surge';
const SCENARIOS: Scenario[] = ['happy_path', 'carrier_failure', 'webhook_timeout', 'bulk_surge'];

// Port 1 is never listening, so this fails fast (connection refused) on
// every attempt without depending on an external service — enough to
// exercise the retry/backoff path without an outbound dependency.
const DEFAULT_TIMEOUT_TARGET = 'http://127.0.0.1:1/sandbox-webhook-timeout-test';
const MAX_BULK_COUNT = 50;
const DEFAULT_BULK_COUNT = 20;

interface Hop {
  status: 'STAGED' | 'PRODUCTION' | 'FAILED';
  delivered: boolean;
  attempts: WebhookDeliveryAttempt[];
}

interface RunOneResult {
  assetId: string;
  finalStatus: string;
  hops: Hop[];
}

async function driveOne(opts: {
  runId: string;
  scenario: Scenario;
  webhookUrl?: string;
  failAt?: 'STAGED' | 'PRODUCTION';
}): Promise<RunOneResult> {
  const asset = await prisma.creativeAsset.create({
    data: {
      title: `Scenario ${opts.scenario} ${opts.runId.slice(0, 8)}`,
      type: 'COPY',
      content: `Synthetic asset generated by /api/sandbox/simulate-scenario (${opts.scenario}).`,
      status: 'DRAFT',
      metadata: { sandboxScenario: opts.scenario, sandboxRunId: opts.runId },
    },
  });

  const hops: Hop[] = [];
  const path: Array<'STAGED' | 'PRODUCTION'> = ['STAGED', 'PRODUCTION'];
  let finalStatus: string = asset.status;

  for (const step of path) {
    const landed: Hop['status'] = opts.failAt === step ? 'FAILED' : step;

    const updated = await prisma.creativeAsset.update({
      where: { id: asset.id },
      data: { status: landed },
    });
    finalStatus = updated.status;

    const event = landed === 'FAILED' ? 'asset.failed' : landed === 'STAGED' ? 'asset.staged' : 'asset.production';
    const result = await dispatchWebhookEvent(
      event,
      { assetId: updated.id, status: updated.status, scenario: opts.scenario, runId: opts.runId },
      updated.organizationId,
      { sign: true, retry: true, targetUrlOverride: opts.webhookUrl }
    );
    hops.push({ status: landed, delivered: result.delivered, attempts: result.attempts });

    if (landed === 'FAILED') break;
  }

  return { assetId: asset.id, finalStatus, hops };
}

export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request format' }, { status: 400 });
  }

  const { scenario, webhookUrl, count } = (body ?? {}) as {
    scenario?: string;
    webhookUrl?: string;
    count?: number;
  };

  if (!scenario || !SCENARIOS.includes(scenario as Scenario)) {
    return NextResponse.json({ error: `scenario must be one of: ${SCENARIOS.join(', ')}` }, { status: 400 });
  }

  const runId = randomUUID();
  const startedAt = Date.now();

  try {
    switch (scenario as Scenario) {
      case 'happy_path': {
        const run = await driveOne({ runId, scenario: 'happy_path', webhookUrl });
        return NextResponse.json({ scenario, runId, durationMs: Date.now() - startedAt, runs: [run] });
      }

      case 'carrier_failure': {
        // Fails midway: STAGED succeeds, the PRODUCTION hop is forced to FAILED.
        const run = await driveOne({ runId, scenario: 'carrier_failure', webhookUrl, failAt: 'PRODUCTION' });
        return NextResponse.json({ scenario, runId, durationMs: Date.now() - startedAt, runs: [run] });
      }

      case 'webhook_timeout': {
        const run = await driveOne({
          runId,
          scenario: 'webhook_timeout',
          webhookUrl: webhookUrl || DEFAULT_TIMEOUT_TARGET,
        });
        return NextResponse.json({ scenario, runId, durationMs: Date.now() - startedAt, runs: [run] });
      }

      case 'bulk_surge': {
        const requested = Math.floor(count ?? DEFAULT_BULK_COUNT);
        const n = Math.min(Math.max(requested, 1), MAX_BULK_COUNT);
        const runs = await Promise.all(
          Array.from({ length: n }, () => driveOne({ runId, scenario: 'bulk_surge', webhookUrl }))
        );
        const succeeded = runs.filter((r) => r.finalStatus === 'PRODUCTION').length;
        return NextResponse.json({
          scenario,
          runId,
          durationMs: Date.now() - startedAt,
          requested: n,
          succeeded,
          failed: n - succeeded,
          runs,
        });
      }
    }
  } catch (err: any) {
    console.error('[SANDBOX_SCENARIO_ERROR]', err);
    return NextResponse.json({ error: err.message || 'Scenario run failed', runId }, { status: 500 });
  }
}
